TagItem and TagList components
storybookjs/design-system pull request #212
Opened 2020-10-15 00:23 UTC by winkerVSbecks

2020-10-15 20:01 UTC, kylesuss commented on src/components/tag/TagItem.tsx
> +};
These are the link props right? Is it worth defining them over there & then importing them in here so we don't duplicate them eventually?

2020-10-15 20:08 UTC, winkerVSbecks commented on src/components/tag/TagItem.tsx
> +};
Was thinking that. The Link is still JS and not TS. Maybe I should switch that over first and then continue with this. Would you consider that a breaking change?

2020-10-15 20:09 UTC, kylesuss commented on src/components/tag/TagList.stories.js
> +      </TagItem>
I'm wondering if the `TagList` should automatically render the `TagItem` 🤔 

Mostly saying that as it mirrors the patterns we have so far, like:

https://github.com/storybookjs/design-system/blob/5bbe65d0bcb0b1526f39bc180c40d64f53d7be67/src/components/LinkTabs.js#L56-L60

That said, I'm open to discussion on it for sure. What was your thought process with this API?

2020-10-15 20:14 UTC, winkerVSbecks commented on src/components/tag/TagList.stories.js
> +      </TagItem>
My intention was to avoid prop drilling. Since, the `TagItem` is a link it can be a regular link or Gatsby Link or Next Link. Which means we would have to pass down a linkWrapper and maybe even have logic around `to` vs `href`. The Tag itself could have an icon, etc. I find this wrapper approach avoids a lot of those headaches and offers a more flexible API.

2020-10-15 20:17 UTC, kylesuss commented on src/components/tag/TagItem.tsx
> +};
That's right. Makes sense then. I'd say leave it if refactoring the Link component is a lot of work at this point. Refactoring it won't break the implementation by any consumers though, right? If that's the case, I wouldn't consider it breaking.

2020-10-15 20:22 UTC, kylesuss commented on src/components/tag/TagList.stories.js
> +      </TagItem>
Yeah that's true. Makes sense. I have run into headaches w/ one of our components that renders links & has the old style prop API (not what you did here) for similar reasons. If for some reason you need to target the underlying link (or tag in this case), it becomes pretty complicated to do that. I'm 👍  w/ this approach -- maybe @domyen has some thoughts as I think he had a hand in some of those original APIs.

2020-10-15 20:23 UTC, kylesuss approved these changes
I'm good on this, pending any API comments from others 👍

2020-10-16 20:45 UTC, domyen commented on src/components/tag/TagList.stories.js
> +      </TagItem>
I'll defer to y'all to make the technical choices. The APIs I designed were intended for a very narrow use case (the Chromatic app) – I wouldn't hold them up as best practice for supporting several apps. 🙇‍♂️

2020-10-16 20:50 UTC, domyen requested changes

2020-10-16 20:50 UTC, domyen commented on src/components/tag/TagItem.stories.js
> +export const WithLinkWrapper = () => <TagItem LinkWrapper={StoryLinkWrapper}>⚛️ React</TagItem>;
- Add a TagItem that isn't a link (we have them on LSB). It looks the same but has no hover behavior.

- Include a dummy url in TagItems that are links so that the behavior is evident. e.g., for regular links include `href="https://chromatic.com"` and for LinkWrapper include `to="https://chromatic.com"`

2020-10-16 20:53 UTC, domyen commented on src/components/tag/TagList.stories.js
> +export const WithMoreTags = () => (
Now would be a good time to use Args

2020-10-16 20:56 UTC, domyen commented on src/components/tag/TagList.stories.js
> +
Should this also include an example with LinkWrapper? We document it in TagItem, but I'd overlook that functionality if it's not called out in a story. 

e.g., I wouldn't know I could use `to="url"` in tandem with `LinkWrapper={StoryLinkWrapper}`

2020-10-20 00:30 UTC, winkerVSbecks commented on src/components/tag/TagItem.tsx
> +};
I opened another PR converting links to TS. Will update once that is merged.

2020-10-20 00:32 UTC, winkerVSbecks commented
@domyen @kylesuss updated with requested changes. I ended up creating a TagLink to handle links. TagItem is the non-interactive version.

2020-10-20 15:23 UTC, kylesuss commented
@winkerVSbecks nice, sounds and looks good to me.

Out of curiosity, Varun, do you think all components in this design system should export themselves as a `forwardRef`? Is that a good goal to work toward? TBH, it feels weird to me to do that but also annoying when you finally end up needing that ref and have to go back and add it.

2020-10-20 15:32 UTC, winkerVSbecks commented
Yea, that seems to be the pattern most DS adopt. Makes sense since they are mostly low level components. That said, typing those components is a pain. 

I don't plan on rewriting everything. We can do that for new components and update old components as and when necessary.

2020-10-20 19:28 UTC, jonniebigodes commented
@winkerVSbecks just checked the latest commit you've made and it looks really great. I'm good with it as well 👍

2020-10-20 20:05 UTC, domyen requested changes

2020-10-20 20:05 UTC, domyen commented on src/components/tag/TagItem.stories.tsx
> +export const WithLinkWrapper = () => <TagItem>⚛️ React</TagItem>;
Is there supposed to be a LinkWrapper around this?

2020-10-20 20:05 UTC, domyen commented on src/components/tag/TagLink.tsx
> +  display: inline-block;
Can we extend TagItem styles instead of repeating them?

2020-10-20 20:09 UTC, domyen commented
Heads up, I'm leaving specific UI comments in Chromatic

2020-11-17 19:40 UTC, winkerVSbecks commented
@domyen updated with changes you requested.

2020-11-18 23:05 UTC, domyen approved these changes

2020-11-19 00:02 UTC, merged

2020-11-20 17:03 UTC, kylesuss commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.2.0`](https://github.com/storybookjs/design-system/releases/tag/v5.2.0) :rocket: