Fix Loading AvatarList Not Showing in Stories
storybookjs/design-system pull request #214
Opened 2020-10-17 00:40 UTC by ahmadatallah

**Description**

A tiny PR for showing the loading avatar-list example in stories as it was not showing and instead, it displays empty avatar-list.

**Checklist**

- [x] Add users and userCount to the loading avatar story. 
- [x] Fix pretty warning for always add parentheses around arrow function (fixed automatically when I run prettier command on the file from my text editor)

2020-10-19 15:11 UTC, kylesuss requested changes
Thanks for the PR! I left a comment about the story args -- let me know what you think.

2020-10-19 15:11 UTC, kylesuss commented on src/components/AvatarList.stories.js
> +Loading.args = { users, userCount: 100, isLoading: true };
```suggestion
Loading.args = { users: undefined, userCount: undefined, isLoading: true };
```

Just took a look at this and I think the `users` and `userCount` are meant to be left undefined for the loading state since in theory we wouldn't know these values during loading.

2020-10-19 22:21 UTC, ahmadatallah commented on src/components/AvatarList.stories.js
> +Loading.args = { users, userCount: 100, isLoading: true };
yes, makes sense. but then, it should be only 
```suggestion
Loading.args = { users: undefined, isLoading: true };
```
as the `userCount` prop is optional!

2020-10-20 15:03 UTC, kylesuss commented on src/components/AvatarList.stories.js
> +Loading.args = { users, userCount: 100, isLoading: true };
Nice one. Sounds good!

2020-10-20 15:03 UTC, kylesuss approved these changes
💯  Thanks for this!

2020-10-20 15:37 UTC, merged

2020-11-20 17:03 UTC, kylesuss commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.2.0`](https://github.com/storybookjs/design-system/releases/tag/v5.2.0) :rocket: