Link ts
storybookjs/design-system pull request #215
Opened 2020-10-19 19:13 UTC by winkerVSbecks

2020-10-20 07:49 UTC, ndelangen requested changes

2020-10-20 07:49 UTC, ndelangen commented on src/components/Link.stories.tsx
> +export const Basic = (args: LinkProps) => <Link {...args} />;
please prefer using the FunctionComponent<Props>

```suggestion
export const Basic: FunctionComponent<LinkProps> = (props) => <Link {...props} />;
```

2020-10-20 07:49 UTC, ndelangen commented on src/components/Link.tsx
> +  StyledLinkProps & {
You should be able to use `ComponentProps<StyledLink>`

2020-10-20 15:25 UTC, kylesuss commented
I defer to @ndelangen on this as he is much more experienced w/ TS than I.

2020-10-21 10:00 UTC, ndelangen commented
LMK if you want to pair on this @winkerVSbecks ?

2020-10-21 17:51 UTC, winkerVSbecks commented on src/components/Link.tsx
> +  StyledLinkProps & {
I couldn't get that working. I get an error: `'StyledLink' refers to a value, but is being used as a type here. Did you mean 'typeof StyledLink'`

2020-10-21 17:58 UTC, winkerVSbecks commented
@ndelangen updated with your suggestions. LMK if this looks good, otherwise would love to pair.

2020-10-22 10:33 UTC, ndelangen approved these changes

2020-10-22 10:33 UTC, ndelangen commented on src/components/Link.stories.tsx
> +import { Link, LinkProps } from './Link';
if possible use `ComponentProps<typeof Link>` over exporting `LinkProps`

2020-10-22 10:33 UTC, ndelangen commented on src/components/Link.tsx
> +/* eslint-disable react/prop-types */
We can tell eslint that this rule doesn't need to be applied at all on .tsx files

2020-10-22 10:33 UTC, ndelangen commented on src/components/Link.tsx
> +};
```suggestion
interface StyledLinkProps {
  containsIcon?: boolean;
  secondary?: boolean;
  tertiary?: boolean;
  nochrome?: boolean;
  inverse?: boolean;
};
```

2020-10-22 10:33 UTC, ndelangen commented on src/components/Link.tsx
> +};
Looks great, some optional improvements, if agree with them 🎉  👍

2020-10-23 19:27 UTC, winkerVSbecks commented
@ndelangen one more update. Added the `LinkComponentPicker` back in. Removing it caused unnecessary props to be padded into the `LinkWrapper`.

2020-10-26 09:50 UTC, ndelangen approved these changes

2020-10-26 09:50 UTC, ndelangen commented
good to merge!

2020-10-26 14:47 UTC, merged

2020-11-20 17:03 UTC, kylesuss commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.2.0`](https://github.com/storybookjs/design-system/releases/tag/v5.2.0) :rocket: