Clipboard components
storybookjs/design-system pull request #222
Opened 2020-11-18 03:45 UTC by winkerVSbecks

* Converted Clipboard to TS
* Ported over ClipboardIcon, ClipboardCode and ClipboardInput

2020-11-18 16:21 UTC, kylesuss approved these changes
👍

2020-11-18 18:35 UTC, domyen requested changes

2020-11-18 18:35 UTC, domyen commented on src/components/clipboard/ClipboadCode.stories.tsx
> +/* eslint-disable import/no-extraneous-dependencies */
This filename is misspelled. `ClipboadCode` --> `ClipboardCode`

2020-11-18 23:02 UTC, domyen approved these changes

2020-11-18 23:25 UTC, merged

2020-11-20 17:03 UTC, kylesuss commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.2.0`](https://github.com/storybookjs/design-system/releases/tag/v5.2.0) :rocket: