Toc
storybookjs/design-system pull request #226
Opened 2020-11-20 15:52 UTC by winkerVSbecks

Mostly just porting over to TS and documenting the top level flat list use case. 

The TS post did require quite a bit of refactoring. I want to make sure I didn't introduce any regressions.

2020-11-21 17:11 UTC, domyen approved these changes

2020-11-21 17:18 UTC, domyen requested changes
Left UI feedback in Chromatic

2020-11-23 09:11 UTC, ndelangen commented on src/components/table-of-contents/TableOfContents.tsx
> +    const isMenuWithChildren = item.type === 'menu' && !!item.children;
Why get rid of the constant in favor of a magic string?

2020-11-23 16:32 UTC, winkerVSbecks commented on src/components/table-of-contents/TableOfContents.tsx
> +    const isMenuWithChildren = item.type === 'menu' && !!item.children;
Good point. I was having some issues with it, but will convert it to enum.

2020-11-25 20:30 UTC, winkerVSbecks commented
@domyen @ndelangen could you take another look at this one please

2020-11-27 13:59 UTC, domyen approved these changes

2020-11-27 18:05 UTC, ndelangen approved these changes

2020-11-27 18:51 UTC, merged

2020-11-28 03:22 UTC, winkerVSbecks commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.4.0`](https://github.com/storybookjs/design-system/releases/tag/v5.4.0) :rocket: